// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrototipoCompras.Data;

#nullable disable

namespace PrototipoCompras.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424170149_ReponerInventarioSeed")]
    partial class ReponerInventarioSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrototipoCompras.Models.AlertaInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventarioProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Resuelta")
                        .HasColumnType("bit");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AlertasInventario");
                });

            modelBuilder.Entity("PrototipoCompras.Models.CostoProveedorHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Producto", "Proveedor", "FechaRegistro");

                    b.ToTable("CostosProveedorHistoricos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaRegistro = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 14500m,
                            Producto = "Laptop Dell",
                            Proveedor = "TechSupply S.A."
                        },
                        new
                        {
                            Id = 2,
                            FechaRegistro = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 14800m,
                            Producto = "Laptop Dell",
                            Proveedor = "TechSupply S.A."
                        },
                        new
                        {
                            Id = 3,
                            FechaRegistro = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 14650m,
                            Producto = "Laptop Dell",
                            Proveedor = "TechSupply S.A."
                        },
                        new
                        {
                            Id = 4,
                            FechaRegistro = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 15050m,
                            Producto = "Laptop Dell",
                            Proveedor = "OfiMundo"
                        },
                        new
                        {
                            Id = 5,
                            FechaRegistro = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 14900m,
                            Producto = "Laptop Dell",
                            Proveedor = "OfiMundo"
                        },
                        new
                        {
                            Id = 6,
                            FechaRegistro = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 15100m,
                            Producto = "Laptop Dell",
                            Proveedor = "OfiMundo"
                        },
                        new
                        {
                            Id = 7,
                            FechaRegistro = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 14380m,
                            Producto = "Laptop Dell",
                            Proveedor = "Distribuidora Central"
                        },
                        new
                        {
                            Id = 8,
                            FechaRegistro = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 14450m,
                            Producto = "Laptop Dell",
                            Proveedor = "Distribuidora Central"
                        },
                        new
                        {
                            Id = 9,
                            FechaRegistro = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 14290m,
                            Producto = "Laptop Dell",
                            Proveedor = "Distribuidora Central"
                        },
                        new
                        {
                            Id = 10,
                            FechaRegistro = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 1900m,
                            Producto = "Monitor LG",
                            Proveedor = "TechSupply S.A."
                        },
                        new
                        {
                            Id = 11,
                            FechaRegistro = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 1940m,
                            Producto = "Monitor LG",
                            Proveedor = "TechSupply S.A."
                        },
                        new
                        {
                            Id = 12,
                            FechaRegistro = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 1925m,
                            Producto = "Monitor LG",
                            Proveedor = "TechSupply S.A."
                        },
                        new
                        {
                            Id = 13,
                            FechaRegistro = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 1980m,
                            Producto = "Monitor LG",
                            Proveedor = "OfiMundo"
                        },
                        new
                        {
                            Id = 14,
                            FechaRegistro = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 1965m,
                            Producto = "Monitor LG",
                            Proveedor = "OfiMundo"
                        },
                        new
                        {
                            Id = 15,
                            FechaRegistro = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 1995m,
                            Producto = "Monitor LG",
                            Proveedor = "OfiMundo"
                        },
                        new
                        {
                            Id = 16,
                            FechaRegistro = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 1880m,
                            Producto = "Monitor LG",
                            Proveedor = "Distribuidora Central"
                        },
                        new
                        {
                            Id = 17,
                            FechaRegistro = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 1895m,
                            Producto = "Monitor LG",
                            Proveedor = "Distribuidora Central"
                        },
                        new
                        {
                            Id = 18,
                            FechaRegistro = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 1875m,
                            Producto = "Monitor LG",
                            Proveedor = "Distribuidora Central"
                        },
                        new
                        {
                            Id = 19,
                            FechaRegistro = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 620m,
                            Producto = "Sillas de oficina",
                            Proveedor = "TechSupply S.A."
                        },
                        new
                        {
                            Id = 20,
                            FechaRegistro = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 635m,
                            Producto = "Sillas de oficina",
                            Proveedor = "TechSupply S.A."
                        },
                        new
                        {
                            Id = 21,
                            FechaRegistro = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 628m,
                            Producto = "Sillas de oficina",
                            Proveedor = "TechSupply S.A."
                        },
                        new
                        {
                            Id = 22,
                            FechaRegistro = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 605m,
                            Producto = "Sillas de oficina",
                            Proveedor = "OfiMundo"
                        },
                        new
                        {
                            Id = 23,
                            FechaRegistro = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 615m,
                            Producto = "Sillas de oficina",
                            Proveedor = "OfiMundo"
                        },
                        new
                        {
                            Id = 24,
                            FechaRegistro = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 610m,
                            Producto = "Sillas de oficina",
                            Proveedor = "OfiMundo"
                        },
                        new
                        {
                            Id = 25,
                            FechaRegistro = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 598m,
                            Producto = "Sillas de oficina",
                            Proveedor = "Distribuidora Central"
                        },
                        new
                        {
                            Id = 26,
                            FechaRegistro = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 602m,
                            Producto = "Sillas de oficina",
                            Proveedor = "Distribuidora Central"
                        },
                        new
                        {
                            Id = 27,
                            FechaRegistro = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecioUnitario = 600m,
                            Producto = "Sillas de oficina",
                            Proveedor = "Distribuidora Central"
                        });
                });

            modelBuilder.Entity("PrototipoCompras.Models.EvaluacionProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Evaluador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("PrototipoCompras.Models.InventarioProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("InventarioProductos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Laptop Dell",
                            Proveedor = "TechSupply S.A.",
                            Stock = 10,
                            StockMinimo = 5,
                            UltimaActualizacion = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Sillas de oficina",
                            Proveedor = "OfiMundo",
                            Stock = 8,
                            StockMinimo = 4,
                            UltimaActualizacion = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Monitor LG",
                            Proveedor = "Distribuidora Central",
                            Stock = 6,
                            StockMinimo = 3,
                            UltimaActualizacion = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PrototipoCompras.Models.NotificacionCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InventarioProductoId")
                        .HasColumnType("int");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("NotificacionesCompra");
                });

            modelBuilder.Entity("PrototipoCompras.Models.OrdenCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InventarioProductoId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SolicitudCompraId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioRecepcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("OrdenesCompra");
                });

            modelBuilder.Entity("PrototipoCompras.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "TechSupply S.A."
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "OfiMundo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Distribuidora Central"
                        });
                });

            modelBuilder.Entity("PrototipoCompras.Models.SolicitudCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GeneradaAutomaticamente")
                        .HasColumnType("bit");

                    b.Property<int?>("InventarioProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("PrototipoCompras.Models.EvaluacionProveedor", b =>
                {
                    b.HasOne("PrototipoCompras.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });
#pragma warning restore 612, 618
        }
    }
}
